"""remove conversation conv_type

Revision ID: 1e1679d8eaeb
Revises: 51f901ca336d
Create Date: 2026-05-07 10:02:40.677128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1679d8eaeb'
down_revision = '51f901ca336d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('conv_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conv_type', sa.VARCHAR(length=30), nullable=False))

    # ### end Alembic commands ###
