"""create base schema for swanflip

Revision ID: 2105d9224644
Revises: 3fe508388660
Create Date: 2026-04-02 13:42:19.129849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2105d9224644'
down_revision = '3fe508388660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('adminId', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('adminId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customer',
    sa.Column('customerId', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.adminId'], ),
    sa.PrimaryKeyConstraint('customerId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('order',
    sa.Column('orderId', sa.String(), nullable=False),
    sa.Column('customerId', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('orderStatus', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customerId'], ['customer.customerId'], ),
    sa.PrimaryKeyConstraint('orderId')
    )
    op.create_table('product',
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('customerId', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customerId'], ['customer.customerId'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('order_product',
    sa.Column('orderProductId', sa.String(), nullable=False),
    sa.Column('orderId', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('numberProdductPerOrder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['order.orderId'], ),
    sa.ForeignKeyConstraint(['productId'], ['product.productId'], ),
    sa.PrimaryKeyConstraint('orderProductId')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('order_product')
    op.drop_table('product')
    op.drop_table('order')
    op.drop_table('customer')
    op.drop_table('admin')
    # ### end Alembic commands ###
