"""remove message_type

Revision ID: 4567a91f6819
Revises: 87c3163be6e3
Create Date: 2026-05-06 20:42:33.595547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4567a91f6819'
down_revision = '87c3163be6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.VARCHAR(length=30), nullable=False))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
