"""Update latest schema

Revision ID: 51f901ca336d
Revises: 4567a91f6819
Create Date: 2026-05-07 09:54:30.711507

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = '51f901ca336d'
down_revision = '4567a91f6819'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    user_columns = {col['name'] for col in sa.inspect(bind).get_columns('users')}

    # Cleanup from previously interrupted SQLite batch operations.
    op.execute(sa.text("DROP TABLE IF EXISTS _alembic_tmp_users"))
    if 'password' not in user_columns:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))

    fallback_hash = generate_password_hash('password123')
    if 'password_hash' in user_columns:
        bind.execute(
            sa.text(
                """
                UPDATE users
                SET password = COALESCE(password, password_hash, :fallback)
                WHERE password IS NULL
                """
            ),
            {'fallback': fallback_hash},
        )
    else:
        bind.execute(
            sa.text(
                """
                UPDATE users
                SET password = :fallback
                WHERE password IS NULL
                """
            ),
            {'fallback': fallback_hash},
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password', existing_type=sa.String(length=255), nullable=False)
        if 'password_hash' in user_columns:
            batch_op.drop_column('password_hash')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
