"""<your_message>

Revision ID: 5d0e25215f40
Revises: c64e6f01e5e4
Create Date: 2026-05-04 14:42:40.704609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0e25215f40'
down_revision = 'c64e6f01e5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('review')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###
