"""<your_message>

Revision ID: 5d0e25215f40
Revises: c64e6f01e5e4
Create Date: 2026-05-04 14:42:40.704609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0e25215f40'
down_revision = 'c64e6f01e5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists to avoid circular dependency
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    msg_columns = {col['name'] for col in inspector.get_columns('messages')}
    prod_columns = {col['name'] for col in inspector.get_columns('products')}
    
    if 'is_read' in msg_columns:
        with op.batch_alter_table('messages', schema=None) as batch_op:
            batch_op.drop_column('is_read')
    
    if 'review' not in prod_columns:
        with op.batch_alter_table('products', schema=None) as batch_op:
            batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    msg_columns = {col['name'] for col in inspector.get_columns('messages')}
    prod_columns = {col['name'] for col in inspector.get_columns('products')}
    
    if 'review' in prod_columns:
        with op.batch_alter_table('products', schema=None) as batch_op:
            batch_op.drop_column('review')
    
    if 'is_read' not in msg_columns:
        with op.batch_alter_table('messages', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###
