"""remove product_id from messages

Revision ID: 908aea90b434
Revises: 6a1b2c3d4e5f
Create Date: 2026-05-13 12:36:20.992710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908aea90b434'
down_revision = '6a1b2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_messages_product_id_products'), type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_messages_product_id_products'), 'products', ['product_id'], ['product_id'])
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
