"""<your_message>

Revision ID: 9bc9382a9c6d
Revises: 2105d9224644
Create Date: 2026-04-22 22:18:42.037749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc9382a9c6d'
down_revision = '2105d9224644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_report', sa.Boolean(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('is_legit', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('product_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.drop_table('customer')
    op.drop_table('order')
    op.drop_table('product')
    op.drop_table('order_product')
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('adminId', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=120), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('adminId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('order_product',
    sa.Column('orderProductId', sa.VARCHAR(), nullable=False),
    sa.Column('orderId', sa.VARCHAR(), nullable=False),
    sa.Column('productId', sa.VARCHAR(), nullable=False),
    sa.Column('numberProdductPerOrder', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['order.orderId'], ),
    sa.ForeignKeyConstraint(['productId'], ['product.productId'], ),
    sa.PrimaryKeyConstraint('orderProductId')
    )
    op.create_table('product',
    sa.Column('productId', sa.VARCHAR(), nullable=False),
    sa.Column('customerId', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('availability', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customerId'], ['customer.customerId'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('order',
    sa.Column('orderId', sa.VARCHAR(), nullable=False),
    sa.Column('customerId', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('orderStatus', sa.VARCHAR(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customerId'], ['customer.customerId'], ),
    sa.PrimaryKeyConstraint('orderId')
    )
    op.create_table('customer',
    sa.Column('customerId', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=120), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.adminId'], ),
    sa.PrimaryKeyConstraint('customerId'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('product_images')
    op.drop_table('messages')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
