"""update is_read to message

Revision ID: c64e6f01e5e4
Revises: 9bc9382a9c6d
Create Date: 2026-05-02 13:20:37.686900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64e6f01e5e4'
down_revision = '9bc9382a9c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists to avoid circular dependency during batch_alter_table
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    msg_columns = {col['name'] for col in inspector.get_columns('messages')}
    
    if 'is_read' not in msg_columns:
        with op.batch_alter_table('messages', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    msg_columns = {col['name'] for col in inspector.get_columns('messages')}
    
    if 'is_read' in msg_columns:
        with op.batch_alter_table('messages', schema=None) as batch_op:
            batch_op.drop_column('is_read')
    # ### end Alembic commands ###
